Get new RelativeFilePaths if previous do not exist
microsoft/winget-create pull request #415
Opened 2023-07-26 18:34 UTC by mdanish-kh

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Are you working against an Issue?
  - #414
-----

2023-07-26 20:46 UTC, mdanish-kh commented
The GitHub diffs are not correct after https://github.com/microsoft/winget-create/pull/415/commits/83973aa632218217c09ea7a330898a3a8e0083c0. I only modified the UpdateSingleInstallerInteractively method but that method had both mixed line endings (CRLF and LF) because of which the diffs are messed up. If you check out the changes in Visual Studio, it'll show you the correct diffs. 
- Related to https://github.com/microsoft/winget-create/issues/391

2023-08-01 23:10 UTC, ryfu-msft requested changes
Just a couple nit comments

2023-08-01 23:10 UTC, ryfu-msft commented on src/WingetCreateCLI/Commands/UpdateCommand.cs
> +                            if (nestedInstaller.RelativeFilePath == null)
nit:
```suggestion
                            if (string.IsNullOrEmpty(nestedInstaller.RelativeFilePath))

```

2023-08-01 23:10 UTC, ryfu-msft commented on src/WingetCreateCLI/Commands/UpdateCommand.cs
> +                string relativePath = matchingFiles.First().Replace(directory, string.Empty).TrimStart('\\');
```suggestion
                string relativePath = matchingFiles.First().Replace(directory, string.Empty).TrimStart(Path.DirectorySeparatorChar);

```

2023-08-01 23:10 UTC, ryfu-msft commented on src/WingetCreateCLI/Commands/UpdateCommand.cs
> +                            if (relativeFilePath == null)
nit:
```suggestion
                if (string.IsNullOrEmpty(packageFile))
```

2023-08-01 23:10 UTC, ryfu-msft commented on src/WingetCreateCLI/Commands/UpdateCommand.cs
> +                            List<string> relativeFilePathsInsideList = installerUpdate.NestedInstallerFiles.Select(x => x.RelativeFilePath).ToList();
Nit: This variable name was slightly confusing for me. I think something like `installerUpdateRelativeFilePathList` might be better.

2023-08-01 23:10 UTC, ryfu-msft commented on src/WingetCreateCLI/Commands/UpdateCommand.cs
> +                            // Skip if the relative path is already in the list.
```suggestion
                            // Skip if the relative path is already in the installer update list.

```

2023-08-01 23:10 UTC, ryfu-msft commented
/azp run

2023-08-01 23:12 UTC, ryfu-msft commented
> The GitHub diffs are not correct after [83973aa](https://github.com/microsoft/winget-create/commit/83973aa632218217c09ea7a330898a3a8e0083c0). I modified the UpdateSingleInstallerInteractively method but that method had both mixed line endings (CRLF and LF) because of which the diffs are messed up. If you check out the changes in Visual Studio, it'll show you the correct diffs.
> 
> * Related to [CRLF line endings for all sources files #391](https://github.com/microsoft/winget-create/issues/391)
> 
> If you like I can fix the line endings for UpdateCommand.cs and PackageParser.cs in a new commit as they are the two most high traffic files, though that'll mess the diffs up even more for this PR

If you can do this in a separate PR (after this gets checked in) that would be a huge help! 🙏 
That way we can link the related issue to that PR when it gets checked in.

2023-08-02 10:47 UTC, mdanish-kh commented
> If you can do this in a separate PR (after this gets checked in) that would be a huge help! 🙏 That way we can link the related issue to that PR when it gets checked in.

Gotcha! Will do after this one. I was shying away from fixing the line endings since it'll mess up the `git blame` output but I guess fixing it has more value.

2023-08-02 16:14 UTC, ryfu-msft commented
/azp run

2023-08-02 16:28 UTC, ryfu-msft commented
/azp run

2023-08-02 16:28 UTC, ryfu-msft approved these changes

2023-08-02 17:14 UTC, merged