Support updating DisplayVersion in autonomous update
microsoft/winget-create pull request #520
Opened 2024-03-10 20:13 UTC by mdanish-kh

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Are you working against an Issue?
	- Resolves #516

### Changes
- Adds `--display-version` CLI arg and support for providing display version with the installer URL
- The value in the installer URL takes precedence over value provided with `--display-version`.
- If a single installer has multiple DisplayVersion entries, we aren't sure which one user is targeting to update. In this case, we only update the first DisplayVersion found.

The thing I struggled the most while making this PR is the correct naming convention to be used. I stayed away from calling the value provided in the installer URL as an "override". Winget-Create does not detect the display-version, so calling it an override didn't make much sense to me. It is extra information user is providing in the URL to update. I went with "Installer URL arguments" as the general term for metadata provided with the installer URL. As such, I had to refactor a bunch of existing stuff. I'm still not sure if that's the correct naming, but I'll leave it up for debate here.

-----

2024-03-11 17:00 UTC, mdanish-kh commented
I think your concern is valid. I like the idea of an input object (https://github.com/microsoft/winget-create/issues/521), but I don't think we can get rid of URL overrides completely. That would be a breaking change for many of current CI/CD's that use this tool. What we may want to do is allow scope & arch as they are, but any additional metadata may need to be specified in an object. I see problems with extending overrides as they are, if I want to add support additional string inputs (not convertible to a known enum value like arch, scope, installerType), then winget-create will have a hard time parsing it with the current implementation. I would like to hear @ryfu-msft's thoughts on this one. I'm not that concerned tho about multiple ways for specifying display version as part of this PR. The both ways function differently, and are not a replica of each other. I believe they offer user flexibility in the sense that if user knows that display version is the same for all installers, then specifying `--display-version` may suffice instead of appending the same version with each URL.

If we don't want to allow this as an override by favoring input object method, maybe we can only take the `--display-version` implementation in this PR

2024-03-11 20:24 UTC, yao-msft commented
The DisplayVersion field in winget package's manifest is used for installed package version mapping. We advise not to use this field unless there's a strong need to. Basically, when winget sees one DisplayVersion defined in the manifest, it tries to download all manifest versions of the package and read all DisplayVersion values, then winget will create ranges of DisplayVersion to map the Installed Package's ARP DisplayVersion, then the installed package version will be mapped to a PackageVersion of the winget manifest for upgradability check.

This operation is a bit expensive on the client.

Also adding DisplayVersion to manifest has possibility to break the winget-pkg publish pipeline if manifest authors do not know the relation between ARP DisplayVersion and winget manifest PackageVersion because winget-pkgs pipeline has integrity check on the DisplayVersion ranges.

Details can be found [here](https://github.com/microsoft/winget-cli/blob/master/doc/specs/%23980%20-%20Apps%20and%20Features%20entries%20version%20mapping.md)

2024-03-12 04:48 UTC, mdanish-kh commented
> Also adding DisplayVersion to manifest has possibility to break the winget-pkg publish pipeline if manifest authors do not know the relation between ARP DisplayVersion and winget manifest PackageVersion because winget-pkgs pipeline has integrity check on the DisplayVersion ranges.

@yao-msft This PR doesn't add support for adding DisplayVersion, it adds support for updating DisplayVersion if the existing manifest already has a DisplayVersion value. In fact, if previous manifest does not have a DisplayVersion value, then the new args will do nothing. This is done to improve the current flow where if an existing manifest contains DisplayVersion field, then winget-create does nothing and leaves the field unchanged in the update flow. This causes the PR to get flagged with error labels over at winget-pkgs since a duplicate DisplayVersion is not allowed within the same PackageIdentifier. User has to manually update this field after creating a PR. This PR improves the UX and allows the user to specify the value while updating the package manifest.

2024-03-12 04:51 UTC, yao-msft commented
> @yao-msft This PR doesn't add support for adding DisplayVersion, it adds support for updating DisplayVersion if the existing manifest already has a DisplayVersion value. In fact, if previous manifest does not have a DisplayVersion value, then the new args will do nothing. This is done to improve the current flow where if an existing manifest contains DisplayVersion field, then winget-create does nothing and leaves the field unchanged in the update flow. This causes the PR to get flagged with error labels over at winget-pkgs since a duplicate DisplayVersion is not allowed within the same PackageIdentifier. User has to manually update this field after creating a PR. This PR improves the UX and allows the user to specify the value while updating the package manifest.


Thanks for the clarification. That's really helpful for reducing errors in winget-pkgs!

2024-07-03 20:08 UTC, ryfu-msft requested changes
Sorry this review is so late, just a couple minor comments but overall great new feature 😄

2024-07-03 20:08 UTC, ryfu-msft commented on src/WingetCreateCore/Common/PackageParser.cs
> +                // New installer will always have a single entry in AppsAndFeaturesEntries
nit: Can you add to this comment explaining that the AppsAndFeaturesEntries for the new installer will not be null if there is a display-version argument present.

2024-07-03 20:08 UTC, ryfu-msft commented on src/WingetCreateCore/Models/InstallerMetadata.cs
> +        /// Gets or sets the display version specified as a CLI arg or an installer argument.
```suggestion
        /// Gets or sets the display version specified as a CLI arg or an installer url argument.

```

2024-07-03 20:08 UTC, ryfu-msft commented on src/WingetCreateTests/WingetCreateTests/UnitTests/UpdateCommandTests.cs
> +            ClassicAssert.IsNull(failedUpdateManifests, "Command should have failed due to multiple display versions specified for a single installer.");
If you take my suggestion above, this error output will be different so be sure to update this test as well.

2024-07-03 20:16 UTC, ryfu-msft commented
/azp run

2024-07-08 17:57 UTC, ryfu-msft commented
/azp run

2024-07-08 18:37 UTC, ryfu-msft commented
/azp run

2024-07-08 18:51 UTC, ryfu-msft approved these changes

2024-07-08 18:51 UTC, merged